services:
  db:
    image: postgres:15
    container_name: muneem_ji_db
    restart: always
    environment:
      - POSTGRES_USER=muneem_admin
      - POSTGRES_PASSWORD=secure_pass_123
      - POSTGRES_DB=muneem_db
    ports:
      # CHANGE HERE: Map host port 5433 to container port 5432
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: